name: 16-autoformat.yml
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

jobs:
  smoke-test:
    uses: ucsb-cs156/workflows/.github/workflows/16-autoformat.yml@dj-autoFormatWithApp
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
