# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: "40-check-production-build: Check Production Build (if this fails, deploying to Dokku will fail)"

env:
  # See: https://github.com/actions/setup-java#supported-distributions
  JAVA_DISTRIBUTION: ${{ vars.JAVA_DISTRIBUTION || 'temurin' }} 

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: szenius/set-timezone@v2.0
      with:
        timezoneLinux: "America/Los_Angeles"
    - uses: actions/checkout@v4
    - name: Set up Java (version from .java-version file)
      uses: actions/setup-java@v4
      with:
         distribution: ${{ env.JAVA_DISTRIBUTION }} 
         java-version-file: ./.java-version
         cache: 'maven'
         cache-dependency-path: 'pom.xml' 
  
    - name: Build with Maven
      env:
        PRODUCTION: true
      run: mvn -ntp -DskipTests clean dependency:list install

  
