name: 42-smoke-test.yml
on:
  workflow_dispatch:
  pull_request:
    paths: [ src/**, pom.xml, lombok.config, frontend/**, .github/workflows/42-smoke-test.yml ]
  push:
    branches: [ main ]
    paths: [ src/**, pom.xml, lombok.config, frontend/**, .github/workflows/42-smoke-test.yml ]

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: devcontainers/ci@v0.3
        with:
          configFile: .devcontainer/production/devcontainer.json
          runCmd: "/home/app/startup.sh /home/app/target/frontiers-1.0.0.jar"